# Generated by Django 5.0.2 on 2024-05-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin2', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='produit',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='valeur',
            new_name='value',
        ),
    ]
