# Generated by Django 5.0.2 on 2024-05-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin2', '0005_rename_date_rating_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('message', models.TextField()),
            ],
        ),
    ]
