# Generated by Django 5.0.2 on 2024-05-07 20:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hs', 'Hespéridés'), ('fl', 'Fleuris'), ('bs', 'boisés'), ('fg', 'fougères'), ('chyp', 'chyprés'), ('or', 'oriental'), ('ar', 'aromatiques')], default='Alimentaire', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(max_length=100)),
                ('description', models.TextField(default='Non définie')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('type', models.CharField(choices=[('hs', 'Hespéridés'), ('fl', 'Fleuris'), ('bs', 'boisés'), ('fg', 'fougères'), ('chyp', 'chyprés'), ('or', 'oriental'), ('ar', 'aromatiques')], default='hs', max_length=9)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('Fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Magfum.fournisseur')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Magfum.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCde', models.DateField(default=datetime.date.today, null=True)),
                ('totalCde', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('produits', models.ManyToManyField(to='Magfum.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magfum.produit')),
            ],
        ),
    ]
