"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path,os
import stripe

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STRIPE_SECRET_KEY_TEST = 'sk_test_51PDZ0RFHHrSpDaSeT9zK3cFsXYL2py2bKFstnlO3bSFOexsrlIjuwRV3ybfbGA5mXlWEpQcyRBjBDnWRQCWcApfD00MAd6WgzV'
PRODUCT_PRICE = 10  # Remplacez 10 par le prix réel de votre produit
REDIRECT_DOMAIN='http://127.0.0.1:8000/'
'''import stripe
stripe.api_key = "sk_test_51PDZ0RFHHrSpDaSeT9zK3cFsXYL2py2bKFstnlO3bSFOexsrlIjuwRV3ybfbGA5mXlWEpQcyRBjBDnWRQCWcApfD00MAd6WgzV"
import stripe
stripe.api_key = "sk_test_51PDZ0RFHHrSpDaSeT9zK3cFsXYL2py2bKFstnlO3bSFOexsrlIjuwRV3ybfbGA5mXlWEpQcyRBjBDnWRQCWcApfD00MAd6WgzV"

stripe.Price.create(
  product='{{PRODUCT_ID}}',
  unit_amount=2000,
  currency="usd",
)
stripe.Price.modify(
  '{{PRICE_ID}}',
  active=False,
)'''
"""stripe.api_key = "sk_test_51PDZ0RFHHrSpDaSeT9zK3cFsXYL2py2bKFstnlO3bSFOexsrlIjuwRV3ybfbGA5mXlWEpQcyRBjBDnWRQCWcApfD00MAd6WgzV"
stripe.checkout.Session.create(
  success_url="https://example.com/success",
  line_items=[{ "price": "price_1N4AEsLkdIwHu7ix7Ssho8Cl","quantity": 2}],
  mode="payment",
)
import stripe
charge = stripe.Charge.retrieve(
  "ch_3Ln3e92eZvKYlo2C0eUfv7bi",
  api_key="sk_test_51PDZ0RFHHrSpDaSeT9zK3cFsXYL2py2bKFstnlO3bSFOexsrlIjuwRV3ybfbGA5mXlWEpQcyRBjBDnWRQCWcApfD00MAd6WgzV"
)
charge.capture() # Uses the same API Key."""



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)6fev7kh*()_ea%th6k$^t*=z=x*biwlp_dekl&=90@knm=!6u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

EMAIL_HOST ='smtp.gmail.com'
EMAIL_HOST_USER ='mkaouar.chayma7@gmail.com'
EMAIL_HOST_PASSWORD ='eyzt digy bair fijk'
EMAIL_PORT='587'
EMAIL_USE_TLS=True
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'magasin.apps.MagasinConfig',
    'Magfum.apps.MagfumConfig',
    'magasin2.apps.Magasin2Config',
    'jeu.apps.JeuConfig',
    'rest_framework',
    'stripe',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'myapp.urls'
MEDIA_ROOT= os.path.join(BASE_DIR, 'media/')
MEDIA_URL= "/media/"
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR,'templates'),
                os.path.join(BASE_DIR,'magasin/templates'),
                os.path.join(BASE_DIR,'Magfum/templates'),
                os.path.join(BASE_DIR,'magasin2/templates'),
                os.path.join(BASE_DIR,'jeu/templates')
                ],


        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                
                
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
	BASE_DIR / "static",'/var/www/static/',os.path.join(BASE_DIR,'magasin/static'),os.path.join(BASE_DIR,'static'),
    BASE_DIR / "static",'/var/www/static/',os.path.join(BASE_DIR,'Magfum/static'),os.path.join(BASE_DIR,'static'),
    BASE_DIR / "static",'/var/www/static/',os.path.join(BASE_DIR,'magasin2/static'),os.path.join(BASE_DIR,'static'),
    BASE_DIR / "static",'/var/www/static/',os.path.join(BASE_DIR,'jeu/static'),os.path.join(BASE_DIR,'static'),
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
